version: '3'

services:

  asistente:
    build:
      context: .
    container_name: asistente
    restart: always
    runtime: nvidia
    network_mode: "host"
    stdin_open: true
    tty: true
    devices:
      - /dev/snd:/dev/snd
    ports:
      - 8080:8080
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/VA
